// navbar and sidebar
export const OPEN_SUBMENU = 'OPEN_SUBMENU';
export const CLOSE_SUBMENU = 'CLOSE_SUBMENU';
export const DETECT_NAVBAR = 'DETECT_NAVBAR';
export const DETECT_FILTER = 'DETECT_FILTER';
export const GET_CATEGORIES = 'GET_CATEGORIES ';
export const IMAGE_MODEL = 'IMAGE_MODEL ';
export const DETECT_IMAGE_MODEL = 'DETECT_IMAGE_MODEL ';
export const ACTIVE_IMAGE_CHANGE = 'ACTIVE_IMAGE_CHANGE ';

// Ads And Single Ad
export const GET_ALLADS_LOADING = 'GET_ALLADS_LOADING';
export const GET_ALLADS_SUCCESS = 'GET_ALLADS_SUCCESS';
export const GET_ALLADS_ERROR = 'GET_ALLADS_ERROR';
export const GET_SINGLE_PRODUCT_LOADING = 'GET_SINGLE_PRODUCT_LOADING';
export const GET_SINGLE_PRODUCT_SUCCESS = 'GET_SINGLEADS_SUCCESS';
export const GET_SINGLE_PRODUCT_ERROR = 'GET_SINGLEADS_ERROR';
export const GET_MORE_ADS_LOADING = 'GET_MORE_LOADING';
export const GET_MORE_ADS = 'GET_MORE_ADS';
export const GET_MORE_ADS_ERROR = 'GET_MORE_ADS_ERROR';
export const FAV_ADS_CHANGE = 'FAV_ADS_CHANGE';
export const CHANGE_DATA_FROM_LOCALSORAGE = 'CHANGE_DATA_FROM_LOCALSORAGE';

// User Token
export const SET_TOKEN = 'SET_TOKEN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_WALLET = 'USER_WALLET';
export const USER_INFO = 'USER_INFO';
export const COUNTRY_CODE = 'COUNTRY_CODE';
export const USER_LOCATION = 'USER_LOCATION';
export const FETCH_FAV_IDS = 'FETCH_FAV_IDS';
export const ADMIN_SUPPORT = 'ADMIN_SUPPORT';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const CHANGE_CHAT_READ = 'CHANGE_CHAT_READ';
export const CHANGE_CLICKED_CHAT = 'CHANGE_CLICKED_CHAT';
export const GET_USERADS_LOAD = 'GET_USERADS_LOAD';
export const GET_USERADS = 'GET_USERADS';
export const GET_USERADS_ERROR = 'GET_USERADS_ERROR';
export const RESET_PAGINATION = 'RESET_PAGINATION';

// Filters
export const LOAD_FILTERED_ADS = 'LOAD_FILTERED_ADS';
export const GET_FILTERED_SUCCESS = 'GET_FILTERED_SUCCESS';
export const GET_FILTERED_ERROR = 'GET_FILTERED_ERROR';
export const GET_PAGINATION_ADS = 'GET_PAGINATION_ADS';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_PRICE_SUCCESS = 'GET_PRICE_SUCCESS';
export const CITY_NAME = 'CITY_NAME';
export const PUT_ADS_IN_FILTER = 'PUT_ADS_IN_FILTER';
export const GET_CITY_SUCCESS = 'GET_CITY_SUCCESS';

// Search
export const GET_SEARCH_SUCCES = 'GET_SEARCH_SUCCES';
export const GET_SEARCH_LOADING = 'GET_SEARCH_LOADING';
export const GET_SEARCH_ERROR = 'GET_SEARCH_ERROR';
export const CLOSE_SEARCH = 'CLOSE_SEARCH';
